embeddings:
  path: C:\Users\sooji\Documents\projects\RAG\embeddings
  model_name: mxbai-embed-large-v1

pdf_folder: C:\Users\sooji\Documents\projects\RAG\sample-documents\diabetes

db_dir: C:\Users\sooji\Documents\projects\RAG\db

vectorstore:
  chroma:
    db_name: "chroma_db"
    collection_name: "diabetes"
  qdrant:
    collection_name: "diabetes"

postprocessors:
  rerank:
    top_n: 7
    path: C:\Users\sooji\Documents\projects\RAG\models
    model: ms-marco-MiniLM-L-12-v2

retrievers:
  vectara:
    similarity_top_k: 15
    n_sentences_before: 2
    n_sentences_after: 2
  summary_doc:
    similarity_top_k: 10
    verbose: true
  fusion:
    mode: reciprocal_rerank
    similarity_top_k: 10
    num_queries: 4
    use_async: true